[build]
  functions = "netlify/functions"

[[headers]]
 const headers = {
  'Access-Control-Allow-Origin': 'https://comtherm-site.webflow.io', // Your Webflow site URL
  'Access-Control-Allow-Headers': 'Content-Type,Authorization',
  'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
  'Content-Type': 'application/json'
};

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200